version: '3'
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "5005:1433"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    container_name: bolton-sql-container
  rabbitmq:
    image: rabbitmq:3.8.14-management
    ports:
      - "5010:5672"
      - "5015:15672"
    container_name: bolton-rabbitmq-container
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: bolton-redis-container
  db:
    container_name: bolton-postgres
    image: postgres
    environment:
      POSTGRES_USER: bolton
      POSTGRES_PASSWORD: bolton
      POSTGRES_DB: bolton
    ports:
      - "5432:5432"

# docker-compose -f docker-compose-local.yml up -d
# docker-compose -f docker-compose-local.yml down

# docker run --name bolton-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres